scp RetrieveData.sh $1:~/RetrieveData.sh
scp Run_CI.sh $1:~/Run_CI.sh
scp run_multiple.sh $1:~/run_multiple.sh
scp run_multipleBIS.sh $1:~/run_multipleBIS.sh
scp analyseCSV.R $1:~/analyseCSV.R
scp retrieveInfo.sh $1:~/retrieveInfo.sh
scp CompileNodes.sh $1:~/CompileNodes.sh
scp test_file.sh $1:~/test_file.sh
scp get_network_csv.sh $1:~/get_network_csv.sh
scp Change_disk.sh $1:~/Change_disk.sh
scp limit.sh $1:~/limit.sh
